from django import template
from datetime import datetime
register = template.Library()

@register.filter(name='split')
def split(value, arg):
    print(arg, value)
    return value.split(arg)

@register.filter(name='date')
def date(value):
    return value.strftime("%Y-%m-%d" )

@register.filter(name='cities')
def cities(value):
    return [
  "Aberdeen",
  "Armagh",
  "Bangor",
  "Bangor",
  "Bath",
  "Belfast",
  "Birmingham",
  "Bradford",
  "Brighton & Hove",
  "Bristol",
  "Cambridge",
  "Canterbury",
  "Cardiff",
  "Carlisle",
  "Chelmsford",
  "Chester",
  "Chichester",
  "City of Gibraltar",
  "Colchester",
  "Coventry",
  "Derby",
  "Doncaster",
  "Douglas",
  "Dundee",
  "Dunfermline",
  "Durham",
  "Ely",
  "Edinburgh",
  "Exeter",
  "Glasgow",
  "Gloucester",
  "Hamilton",
  "Hereford",
  "Inverness",
  "Jamestown",
  "Kingston-upon-Hull",
  "Lancaster",
  "Leeds",
  "Leicester",
  "Lichfield",
  "Lincoln",
  "Lisburn",
  "Londonderry",
  "London",
  "Manchester",
  "Milton Keynes",
  "Newcastle-upon-Tyne",
  "Newport",
  "Newry",
  "Norwich",
  "Nottingham",
  "Oxford",
  "Perth",
  "Peterborough",
  "Plymouth",
  "Portsmouth",
  "Preston",
  "Ripon",
  "Salford",
  "Salisbury",
  "Sheffield",
  "Southampton",
  "Southend-on-Sea",
  "St Albans",
  "St Asaph",
  "St Davids",
  "Stanley",
  "Stirling",
  "Stoke on Trent",
  "Sunderland",
  "Swansea",
  "Truro",
  "Wakefield",
  "Wells",
  "Westminster",
  "Wolverhampton",
  "Worcester",
  "Wrexham",
  "York"
]

@register.filter(name='countries')
def countries(value):
    return [
        'United Kingdom',

'England',

'Scotland',

'Wales',

'Northern Ireland'
]

@register.filter(name='countys')
def countys(value):
    return [
  "Aberdeenshire",
  "Anglesey",
  "Angus (Forfarshire)",
  "Antrim",
  "Argyllshire",
  "Armagh",
  "Ayrshire",
  "Banffshire",
  "Bedfordshire",
  "Berkshire",
  "Berwickshire",
  "Breconshire",
  "Buckinghamshire",
  "Buteshire",
  "Caernarvonshire",
  "Caithness",
  "Cambridgeshire",
  "Cardiganshire",
  "Carmarthenshire",
  "Cheshire",
  "Clackmannanshire",
  "Cornwall",
  "Cumberland",
  "Denbighshire",
  "Derbyshire",
  "Devon",
  "Dorset",
  "Down",
  "Dumfriesshire",
  "Dunbartonshire",
  "Durham",
  "East Lothian",
  "East Riding of Yorkshire",
  "East Sussex",
  "Essex",
  "Fermanagh",
  "Fife",
  "Flintshire",
  "Glamorgan",
  "Gloucestershire",
  "Greater London",
  "Greater Manchester",
  "Hampshire",
  "Herefordshire",
  "Hertfordshire",
  "Huntingdonshire",
  "Inverness-shire",
  "Isle of Wight",
  "Kent",
  "Kincardineshire",
  "Kinross-shire",
  "Kirkcudbrightshire",
  "Lanarkshire",
  "Lancashire",
  "Leicestershire",
  "Lincolnshire",
  "Londonderry",
  "Merionethshire",
  "Merseyside",
  "Midlothian",
  "Monmouthshire",
  "Montgomeryshire",
  "Morayshire",
  "Nairnshire",
  "Norfolk",
  "Northamptonshire",
  "Northumberland",
  "Nottinghamshire",
  "Orkney",
  "Oxfordshire",
  "Peeblesshire",
  "Pembrokeshire",
  "Perthshire",
  "Radnorshire",
  "Renfrewshire",
  "Ross & Cromarty",
  "Roxburghshire",
  "Rutland",
  "Selkirkshire",
  "Shetland",
  "Shropshire",
  "Somerset",
  "Staffordshire",
  "Stirlingshire",
  "Suffolk",
  "Surrey",
  "Sutherland",
  "Tyne & Wear",
  "Tyrone",
  "Warwickshire",
  "West Lothian",
  "West Midlands",
  "West Riding of Yorkshire",
  "West Sussex",
  "Westmorland",
  "Wigtownshire",
  "Wiltshire",
  "Worcestershire",
  "Yorkshire"
]