# Generated by Django 5.0.1 on 2024-10-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('postcode', models.CharField(blank=True, max_length=255, null=True)),
                ('house_name', models.CharField(blank=True, max_length=255, null=True)),
                ('street_name', models.TextField(blank=True, max_length=999, null=True)),
                ('address', models.TextField(blank=True, max_length=999, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('county', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('constituency', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_customer', models.BooleanField(default=False)),
                ('energy_rating', models.CharField(blank=True, max_length=2, null=True)),
                ('energy_certificate_link', models.URLField(blank=True, max_length=999, null=True)),
                ('recommendations', models.TextField(blank=True, max_length=999, null=True)),
                ('stage_values', models.JSONField(blank=True, null=True)),
                ('closed', models.BooleanField(default=False)),
                ('imported', models.BooleanField(default=False)),
            ],
        ),
    ]
