# Generated by Django 5.0.1 on 2024-10-09 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_app', '0003_initial'),
        ('customer_app', '0001_initial'),
        ('funding_route_app', '0002_initial'),
        ('home', '0001_initial'),
        ('product_app', '0001_initial'),
        ('question_actions_requirements_app', '0001_initial'),
        ('region_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='product_app.product'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='question_actions_requirements_app.questions'),
        ),
        migrations.AddField(
            model_name='answer',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='funding_route_app.route'),
        ),
        migrations.AddField(
            model_name='answer',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='home.stage'),
        ),
        migrations.AddField(
            model_name='customers',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customers',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customers',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='home.campaign'),
        ),
        migrations.AddField(
            model_name='customers',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='client_app.clients'),
        ),
        migrations.AddField(
            model_name='customers',
            name='council',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='region_app.councils'),
        ),
        migrations.AddField(
            model_name='customers',
            name='parent_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customer_app.customers'),
        ),
        migrations.AddField(
            model_name='customers',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='funding_route_app.route'),
        ),
        migrations.AddField(
            model_name='answer',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='customer_app.customers'),
        ),
    ]
