# Generated by Django 5.0.1 on 2024-11-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_app", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="uploads/answers"),
        ),
    ]
