# Generated by Django 5.0.1 on 2024-12-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0007_alter_answer_customer_alter_answer_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='submit',
            field=models.BooleanField(default=False),
        ),
    ]
