# Generated by Django 5.0.1 on 2024-11-14 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_app', '0010_remove_clients_assigned_to_clients_assigned_to'),
        ('funding_route_app', '0003_initial'),
        ('home', '0002_initial'),
        ('product_app', '0001_initial'),
        ('question_actions_requirements_app', '0003_questions_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CJStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CJStage', to='client_app.clients')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CJStage', to='product_app.product')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='question_actions_requirements_app.questions')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CJStage', to='funding_route_app.route')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CJStage', to='home.stage')),
            ],
        ),
    ]
