# Generated by Django 5.0.1 on 2024-11-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_journey_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cjstage',
            name='questions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
