# Generated by Django 5.0.1 on 2024-10-09 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_journey_app', '0001_initial'),
        ('funding_route_app', '0002_initial'),
        ('home', '0001_initial'),
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cjstage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CJStage', to='product_app.product'),
        ),
        migrations.AddField(
            model_name='cjstage',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CJStage', to='funding_route_app.route'),
        ),
        migrations.AddField(
            model_name='cjstage',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CJStage', to='home.stage'),
        ),
    ]
