# Generated by Django 5.0.1 on 2024-11-08 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_journey_app', '0002_initial'),
        ('question_actions_requirements_app', '0003_questions_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cjstage',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CJStage', to='question_actions_requirements_app.questions'),
        ),
    ]
