# Generated by Django 5.0.1 on 2024-11-22 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_journey_app', '0002_cjstage_questions'),
        ('security_app', '0007_role_new_suggestion_role_suggestion_role_suggestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='cjstage',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='security_app.role'),
        ),
    ]
