# Generated by Django 5.0.1 on 2024-11-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_journey_app', '0003_cjstage_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cjstage',
            name='question',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
