# Generated by Django 5.0.1 on 2024-11-28 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0012_alter_clientarchive_client_and_more'),
        ('customer_journey_app', '0003_cjstage_role'),
        ('funding_route_app', '0003_initial'),
        ('home', '0009_alter_action_agent_alter_cities_agent_and_more'),
        ('product_app', '0001_initial'),
        ('question_actions_requirements_app', '0005_questions_is_client_archive'),
        ('security_app', '0007_role_new_suggestion_role_suggestion_role_suggestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cjstage',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CJStage', to='client_app.clients'),
        ),
        migrations.AlterField(
            model_name='cjstage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CJStage', to='product_app.product'),
        ),
        migrations.AlterField(
            model_name='cjstage',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='question_actions_requirements_app.questions'),
        ),
        migrations.AlterField(
            model_name='cjstage',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='security_app.role'),
        ),
        migrations.AlterField(
            model_name='cjstage',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CJStage', to='funding_route_app.route'),
        ),
        migrations.AlterField(
            model_name='cjstage',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CJStage', to='home.stage'),
        ),
    ]
