# Generated by Django 5.0.1 on 2024-12-03 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_journey_app', '0004_alter_cjstage_client_alter_cjstage_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cjstage',
            name='question',
        ),
    ]
