# Generated by Django 5.0.1 on 2024-11-09 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_app", "0010_remove_clients_assigned_to_clients_assigned_to"),
        ("customer_journey_app", "0004_alter_cjstage_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="cjstage",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="CJStage",
                to="client_app.clients",
            ),
        ),
    ]
