# Generated by Django 5.0.1 on 2024-11-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_journey_app', '0005_cjstage_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cjstage',
            name='question',
        ),
        migrations.AddField(
            model_name='cjstage',
            name='questions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
