from django.contrib import admin
from .models import (
    Action,
    Customers,
    Clients,
    Campaign,
    Councils,
    Route,
    Stage,
    Document,
    Cities,
    HistoryId,
    Countys,
    Countries,
    Signature,
    Product,
    CoverageAreas,
    Questions,
    Rule_Regulation,
    ClientArchive,
    Client_Council_Route,
)

admin.site.register(Action)
admin.site.register(Customers)
admin.site.register(Clients)
admin.site.register(Campaign)
admin.site.register(Councils)
admin.site.register(Route)
admin.site.register(Stage)
admin.site.register(Document)
admin.site.register(Cities)
admin.site.register(HistoryId)
admin.site.register(Countys)
admin.site.register(Countries)
admin.site.register(Signature)
admin.site.register(Product)
admin.site.register(CoverageAreas)
admin.site.register(Questions)
admin.site.register(Rule_Regulation)
admin.site.register(ClientArchive)
admin.site.register(Client_Council_Route)