# Generated by Django 5.0.1 on 2024-12-06 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_alter_signature_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='employee',
            field=models.ManyToManyField(blank=True, null=True, related_name='signature', to=settings.AUTH_USER_MODEL),
        ),
    ]
