# Generated by Django 5.0.1 on 2024-11-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_actions_requirements_app', '0003_questions_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
