# Generated by Django 5.0.1 on 2024-11-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_actions_requirements_app', '0004_questions_is_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='is_client_archive',
            field=models.BooleanField(default=False),
        ),
    ]
