# Generated by Django 5.0.1 on 2024-11-28 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding_route_app', '0003_initial'),
        ('home', '0010_alter_action_agent_alter_action_client_and_more'),
        ('product_app', '0001_initial'),
        ('question_actions_requirements_app', '0005_questions_is_client_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule_regulation',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules_regulation', to='product_app.product'),
        ),
        migrations.AlterField(
            model_name='rule_regulation',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules_regulation', to='question_actions_requirements_app.questions'),
        ),
        migrations.AlterField(
            model_name='rule_regulation',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules_regulation', to='funding_route_app.route'),
        ),
        migrations.AlterField(
            model_name='rule_regulation',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules_regulation', to='home.stage'),
        ),
    ]
