from django.db import models
from user.models import User

class Role(models.Model):
    name = models.CharField(max_length=100, blank=True, null=True)
    dashboard = models.BooleanField(default=False)
    mcustomer = models.BooleanField(default=False)
    customer = models.BooleanField(default=False)
    archive = models.BooleanField(default=False)
    client = models.BooleanField(default=False)
    council = models.BooleanField(default=False)
    admin = models.BooleanField(default=False)
    product = models.BooleanField(default=False)
    globals = models.BooleanField(default=False)
    finance = models.BooleanField(default=False)
    hr = models.BooleanField(default=False)
    security = models.BooleanField(default=False)
    funding_route = models.BooleanField(default=False)
    CJ = models.BooleanField(default=False)
    QA = models.BooleanField(default=False)
    h_dashboard = models.BooleanField(default=False)
    h_employee = models.BooleanField(default=False)
    h_application = models.BooleanField(default=False)
    h_onboarding = models.BooleanField(default=False)
    h_timesheet = models.BooleanField(default=False)
    h_emp_action = models.BooleanField(default=False)
    h_emp_notify = models.BooleanField(default=False)
    h_offboarding = models.BooleanField(default=False)
    h_org_chart = models.BooleanField(default=False)
    knowledge_base = models.BooleanField(default=False)
    s_employee = models.BooleanField(default=False)
    s_role = models.BooleanField(default=False)
    s_client = models.BooleanField(default=False)

