# Generated by Django 5.0.1 on 2024-11-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0002_alter_employee_user_employee_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onboarding', models.CharField(blank=True, max_length=100, null=True)),
                ('probation', models.CharField(blank=True, max_length=100, null=True)),
                ('regularised', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
