# Generated by Django 5.0.1 on 2024-11-01 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0003_emergency_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='personal_phone',
            new_name='personal_phon',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='position',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
    ]
