# Generated by Django 5.0.1 on 2024-11-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0006_employee_onboarding_employee_probation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='compassionate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='duvey',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='holiday',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='sick',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
