# Generated by Django 5.0.1 on 2024-11-02 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0008_employee_requests_duration_employee_requests_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='requests_duration',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='requests_hours',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='requests_leave_file',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='requests_leave_type',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='requests_status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='time_off_accrued',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='time_off_beginning_balance',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='time_off_current_balance',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='time_off_scheduled',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='time_off_summary_leave_type',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='time_off_used',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='upcoming_duration',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='upcoming_hours',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='upcoming_leave_file',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='upcoming_leave_type',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='upcoming_status',
        ),
        migrations.CreateModel(
            name='Requests_time_off',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.DateTimeField(blank=True, null=True)),
                ('hours', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('leave_file', models.FileField(blank=True, null=True, upload_to='leave_files')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hr_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Time_off_summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(blank=True, max_length=100, null=True)),
                ('beginning_balance', models.IntegerField(blank=True, null=True)),
                ('accrued', models.IntegerField(blank=True, null=True)),
                ('used', models.IntegerField(blank=True, null=True)),
                ('scheduled', models.IntegerField(blank=True, null=True)),
                ('current_balance', models.IntegerField(blank=True, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hr_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Upcoming_time_off',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.DateTimeField(blank=True, null=True)),
                ('hours', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('leave_file', models.FileField(blank=True, null=True, upload_to='leave_files')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hr_app.employee')),
            ],
        ),
    ]
