# Generated by Django 5.0.1 on 2024-11-02 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0009_remove_employee_requests_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests_time_off',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_requests_time_off', to='hr_app.employee'),
        ),
        migrations.AlterField(
            model_name='time_off_summary',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_time_off_summary', to='hr_app.employee'),
        ),
        migrations.AlterField(
            model_name='upcoming_time_off',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_upcoming_time_off', to='hr_app.employee'),
        ),
    ]
