# Generated by Django 5.0.1 on 2024-11-02 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0010_alter_requests_time_off_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('completed', models.TextField(blank=True, null=True)),
                ('view_certificate', models.FileField(blank=True, null=True, upload_to='certificates')),
                ('assigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_courses', to='hr_app.employee')),
            ],
        ),
    ]
