# Generated by Django 5.0.1 on 2024-11-02 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0011_courses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emergency_status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emergency_contact',
        ),
        migrations.AddField(
            model_name='emergency_contact',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_emergency_contact', to='hr_app.employee'),
        ),
    ]
