# Generated by Django 5.0.1 on 2024-11-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0012_delete_emergency_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='postal_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
