# Generated by Django 5.0.1 on 2024-11-28 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0012_alter_clientarchive_client_and_more'),
        ('home', '0010_alter_action_agent_alter_action_client_and_more'),
        ('hr_app', '0014_alter_employee_reporting_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_courses', to='hr_app.employee'),
        ),
        migrations.AlterField(
            model_name='emergency_contact',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_emergency_contact', to='hr_app.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.action'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_app.clients'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='reporting_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_reporting_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee_action',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee_action',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_app.employee'),
        ),
        migrations.AlterField(
            model_name='requests_time_off',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_requests_time_off', to='hr_app.employee'),
        ),
        migrations.AlterField(
            model_name='time_off_summary',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_time_off_summary', to='hr_app.employee'),
        ),
        migrations.AlterField(
            model_name='upcoming_time_off',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_upcoming_time_off', to='hr_app.employee'),
        ),
    ]
