# Generated by Django 5.0.1 on 2024-10-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('question_actions_requirements_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='question',
            field=models.ManyToManyField(related_name='stage', to='question_actions_requirements_app.questions'),
        ),
    ]
