# Generated by Django 5.0.1 on 2024-11-22 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_suggestion_priority_sub_suggestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='suggestion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.suggestion'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='expected_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
