# Generated by Django 5.0.1 on 2024-11-27 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_action_suggestion_suggestion_archive_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='archive',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='aditional_requesters',
            field=models.ManyToManyField(blank=True, related_name='aditional_requesters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_to_suggestion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='requested',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
