# Generated by Django 5.0.1 on 2024-11-27 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_suggestion_archive_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_suggestions',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_to_sub_suggestion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sub_suggestions',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
