# Generated by Django 5.0.1 on 2024-11-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_sub_suggestions_assigned_to_sub_suggestions_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_suggestions',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
