# Generated by Django 5.0.1 on 2024-11-28 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0012_alter_clientarchive_client_and_more'),
        ('customer_app', '0007_alter_answer_customer_alter_answer_product_and_more'),
        ('funding_route_app', '0003_initial'),
        ('home', '0009_alter_action_agent_alter_cities_agent_and_more'),
        ('region_app', '0002_alter_councils_agent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='action',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_app.clients'),
        ),
        migrations.AlterField(
            model_name='action',
            name='council',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region_app.councils'),
        ),
        migrations.AlterField(
            model_name='action',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_app.customers'),
        ),
        migrations.AlterField(
            model_name='action',
            name='suggestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.suggestion'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='client_app.clients'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client_council_route',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_council_route', to='client_app.clients'),
        ),
        migrations.AlterField(
            model_name='client_council_route',
            name='council',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_council_route', to='region_app.councils'),
        ),
        migrations.AlterField(
            model_name='client_council_route',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_council_route', to='funding_route_app.route'),
        ),
        migrations.AlterField(
            model_name='countries',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='countys',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stage',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage', to='client_app.clients'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='council',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage', to='region_app.councils'),
        ),
        migrations.AlterField(
            model_name='sub_suggestions',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to_sub_suggestion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sub_suggestions',
            name='suggestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_suggestions', to='home.suggestion'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_suggestion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to_suggestion', to=settings.AUTH_USER_MODEL),
        ),
    ]
