# Generated by Django 5.0.1 on 2024-12-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_action_agent_alter_action_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='suggestion', to='home.document'),
        ),
    ]
