# Generated by Django 5.0.1 on 2024-11-30 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_action_agent_alter_action_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.document'),
        ),
    ]
