# Generated by Django 5.0.1 on 2024-11-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_suggestion_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='file',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='file',
            field=models.ManyToManyField(blank=True, null=True, to='home.document'),
        ),
    ]
