# Generated by Django 5.0.1 on 2024-12-03 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_suggestion_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='file',
        ),
    ]
