# Generated by Django 5.0.1 on 2024-10-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=999, null=True)),
                ('managed_by', models.CharField(blank=True, max_length=999, null=True)),
                ('main_contact', models.CharField(blank=True, max_length=999, null=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=999, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('global_archive', models.BooleanField(default=False)),
            ],
        ),
    ]
