# Generated by Django 5.0.1 on 2024-10-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funding_route_app', '0001_initial'),
        ('region_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='council',
            field=models.ManyToManyField(related_name='routes', to='region_app.councils'),
        ),
    ]
