# Generated by Django 5.0.1 on 2024-10-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funding_route_app', '0002_initial'),
        ('home', '0001_initial'),
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='documents',
            field=models.ManyToManyField(related_name='route', to='home.document'),
        ),
        migrations.AddField(
            model_name='route',
            name='product',
            field=models.ManyToManyField(related_name='route', to='product_app.product'),
        ),
    ]
