# Generated by Django 5.0.1 on 2024-10-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('dashboard', models.BooleanField(default=False)),
                ('customer', models.BooleanField(default=False)),
                ('client', models.BooleanField(default=False)),
                ('council', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('product', models.BooleanField(default=False)),
                ('globals', models.BooleanField(default=False)),
                ('finance', models.BooleanField(default=False)),
                ('hr', models.BooleanField(default=False)),
                ('security', models.BooleanField(default=False)),
            ],
        ),
    ]
