# Generated by Django 5.0.1 on 2024-10-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='CJ',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='QA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='funding_route',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='h_application',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='h_dashboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='h_emp_action',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='h_emp_notify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='h_employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='h_offboarding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='h_onboarding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='h_org_chart',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='h_timesheet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='knowledge_base',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='mcustomer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='s_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='s_employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='s_role',
            field=models.BooleanField(default=False),
        ),
    ]
