# Generated by Django 5.0.1 on 2024-10-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0002_role_cj_role_qa_role_funding_route_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
