# Generated by Django 5.0.1 on 2024-11-01 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
        ('security_app', '0004_emergency_contact_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.action'),
        ),
    ]
