# Generated by Django 5.0.1 on 2024-11-01 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0005_employee_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='action',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='client',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.DeleteModel(
            name='Emergency_contact',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
