# Generated by Django 5.0.1 on 2024-11-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0006_remove_employee_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='new_suggestion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='suggestion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='suggestions',
            field=models.BooleanField(default=False),
        ),
    ]
