# Generated by Django 5.0.1 on 2024-10-09 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_app', '0001_initial'),
        ('region_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientarchive',
            name='councils',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_archive', to='region_app.councils'),
        ),
    ]
