# Generated by Django 5.0.1 on 2024-10-09 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_app', '0002_initial'),
        ('funding_route_app', '0002_initial'),
        ('home', '0001_initial'),
        ('product_app', '0001_initial'),
        ('region_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientarchive',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_archive', to='product_app.product'),
        ),
        migrations.AddField(
            model_name='clientarchive',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_archive', to='funding_route_app.route'),
        ),
        migrations.AddField(
            model_name='clientarchive',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_archive', to='home.stage'),
        ),
        migrations.AddField(
            model_name='clients',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clients',
            name='council',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='region_app.councils'),
        ),
        migrations.AddField(
            model_name='clients',
            name='parent_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='client_app.clients'),
        ),
        migrations.AddField(
            model_name='clients',
            name='product',
            field=models.ManyToManyField(related_name='client', to='product_app.product'),
        ),
        migrations.AddField(
            model_name='clients',
            name='route',
            field=models.ManyToManyField(related_name='client', to='funding_route_app.route'),
        ),
        migrations.AddField(
            model_name='clientarchive',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_archive', to='client_app.clients'),
        ),
        migrations.AddField(
            model_name='coverageareas',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_areas', to='client_app.clients'),
        ),
        migrations.AddField(
            model_name='coverageareas',
            name='council',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='region_app.councils'),
        ),
    ]
