# Generated by Django 5.0.1 on 2024-10-31 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0004_clients_client_user_clients_user_alter_clients_agent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
