# Generated by Django 5.0.1 on 2024-11-01 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0007_alter_clients_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='clients',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='client_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
