# Generated by Django 5.0.1 on 2024-11-28 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0011_alter_clients_agent_alter_clients_client_user'),
        ('funding_route_app', '0003_initial'),
        ('home', '0009_alter_action_agent_alter_cities_agent_and_more'),
        ('product_app', '0001_initial'),
        ('region_app', '0002_alter_councils_agent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientarchive',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_archive', to='client_app.clients'),
        ),
        migrations.AlterField(
            model_name='clientarchive',
            name='councils',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_archive', to='region_app.councils'),
        ),
        migrations.AlterField(
            model_name='clientarchive',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_archive', to='product_app.product'),
        ),
        migrations.AlterField(
            model_name='clientarchive',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_archive', to='funding_route_app.route'),
        ),
        migrations.AlterField(
            model_name='clientarchive',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_archive', to='home.stage'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_as_agent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clients',
            name='client_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clients',
            name='parent_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='client_app.clients'),
        ),
        migrations.AlterField(
            model_name='coverageareas',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coverage_areas', to='client_app.clients'),
        ),
        migrations.AlterField(
            model_name='coverageareas',
            name='council',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region_app.councils'),
        ),
    ]
