# Generated by Django 5.0.1 on 2024-02-04 05:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_customer_customers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='date',
        ),
        migrations.AddField(
            model_name='action',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
