# Generated by Django 5.0.1 on 2024-02-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_action_date_action_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
