# Generated by Django 5.0.1 on 2024-01-18 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='admin@gmail.com', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
