# Generated by Django 5.0.1 on 2024-01-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='customer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dashboard',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='finance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='hr',
            field=models.BooleanField(default=False),
        ),
    ]
