# Generated by Django 5.0.1 on 2024-02-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='council',
            field=models.BooleanField(default=False),
        ),
    ]
