# Generated by Django 5.0.1 on 2024-03-05 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_council'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='council',
            new_name='funding_route',
        ),
    ]
