# Generated by Django 5.0.1 on 2024-03-12 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_council_user_funding_route'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='funding_route',
            new_name='council',
        ),
    ]
