# Generated by Django 5.0.1 on 2024-10-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_is_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
