# Generated by Django 5.0.1 on 2024-10-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_user_is_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='globals',
            field=models.BooleanField(default=False),
        ),
    ]
