# Generated by Django 5.0.1 on 2024-10-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_user_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='approved',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
