# Generated by Django 5.0.1 on 2024-10-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_user_cj_user_qa_user_h_application_user_h_dashboard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
    ]
