# Generated by Django 5.0.1 on 2024-11-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_user_is_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_suggestion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='suggestion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='suggestions',
            field=models.BooleanField(default=False),
        ),
    ]
